
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author EVARISTO
 */
public class GerenciamentoQuarto extends javax.swing.JFrame {

    Connection conn;
    Statement st;
    PreparedStatement ps;
    ResultSet rs;
    
    public GerenciamentoQuarto() {
        initComponents();
        try {
            conn=DriverManager.getConnection("jdbc:mysql://localhost/hotel?user=root&password=");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro de conexao em: "+e.getMessage());
        }
        ColocarnaTabela();
    }
    public void ColocarnaTabela(){
        int c=0;
        
        try {
            ps=conn.prepareStatement("select * from quartos");
            rs=ps.executeQuery();
            
            ResultSetMetaData rsmd= rs.getMetaData();
            c=rsmd.getColumnCount();
            DefaultTableModel tb= (DefaultTableModel) tabela.getModel();
            tb.setRowCount(0);
            
            while(rs.next()){
                Vector coluna= new Vector();
                
                for(int i=0;i<=c;i++){
                    coluna.add(rs.getString("numquarto"));
                    coluna.add(rs.getString("tipoq"));
                    coluna.add(rs.getString("cama"));
                    coluna.add(rs.getString("preco"));
                    coluna.add(rs.getString("estado"));
                }
                tb.addRow(coluna);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnumquarto = new javax.swing.JTextField();
        cmbq = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbcama = new javax.swing.JComboBox<>();
        txtpreco = new javax.swing.JTextField();
        btAdicionar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_management_64px_1.png"))); // NOI18N
        jLabel1.setText("GERENCIAMENTO DE QUARTOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 370, 80));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_cancel_48px_1.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(975, 0, 49, 40));

        tabela.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero de Quarto", "Tipo do Quarto", "Cama", "Preco", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 102, 840, 366));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Numero de Quarto");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Tipo de Quarto");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, -1, -1));

        txtnumquarto.setBackground(new java.awt.Color(240, 240, 240));
        txtnumquarto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtnumquarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumquartoActionPerformed(evt);
            }
        });
        getContentPane().add(txtnumquarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, 113, 30));

        cmbq.setBackground(new java.awt.Color(240, 240, 240));
        cmbq.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Com AC", "Sem AC" }));
        getContentPane().add(cmbq, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, 127, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Preco");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 480, 80, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Cama");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, -1, -1));

        cmbcama.setBackground(new java.awt.Color(240, 240, 240));
        cmbcama.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbcama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro", "Casal" }));
        getContentPane().add(cmbcama, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 600, 110, 30));

        txtpreco.setBackground(new java.awt.Color(240, 240, 240));
        txtpreco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtpreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecoActionPerformed(evt);
            }
        });
        getContentPane().add(txtpreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 510, 90, 30));

        btAdicionar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btAdicionar.setForeground(new java.awt.Color(0, 0, 255));
        btAdicionar.setText("Adicionar Detalhes do Quarto");
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(btAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 600, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Voltar ao menu principal");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 640, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/green-landscape-wallpaper-2560x1600-1626_7.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1040, 670));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtnumquartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumquartoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumquartoActionPerformed

    private void txtprecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprecoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new PaginaInicial().setVisible(true);
         dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         int sim=JOptionPane.showConfirmDialog(this, "Tem certeza que quer sair desta pagina?","SAIR",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(sim==JOptionPane.YES_OPTION)
       System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        if(txtnumquarto.getText().equals("")){
            JOptionPane.showMessageDialog(null, "E Obrigatorio Preecher todos os Campos!");
            txtnumquarto.requestFocus();
            
        }
       
       else if(txtpreco.getText().equals("")){
            JOptionPane.showMessageDialog(null, "E Obrigatorio Preecher todos os Campos!");
            txtpreco.requestFocus();
        }
       else{
            try {
                ps=conn.prepareStatement("select * from quartos where numquarto=?");
                ps.setString(1, txtnumquarto.getText());
                rs=ps.executeQuery();
                
                if(rs.next()){
                    JOptionPane.showMessageDialog(null, "O Quarto ja esta ocupado, tenta outro");
                }else{
                    ps=conn.prepareStatement("insert into quartos(numquarto,tipoq,cama,preco,estado) values(?,?,?,?,?)");
                    ps.setString(1, txtnumquarto.getText());
                    ps.setString(2, cmbq.getItemAt(cmbq.getSelectedIndex()));
                    ps.setString(3, cmbcama.getItemAt(cmbcama.getSelectedIndex()));
                    ps.setString(4, txtpreco.getText());
                    ps.setString(5, "Nao Reservado");
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Adicionado com Sucesso");
                    txtnumquarto.setText("");
                    txtpreco.setText("");
                    ColocarnaTabela();
                }
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "erro na insercao em: "+e.getMessage());
            }
           
       }
        
    }//GEN-LAST:event_btAdicionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoQuarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoQuarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoQuarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoQuarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciamentoQuarto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JComboBox<String> cmbcama;
    private javax.swing.JComboBox<String> cmbq;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txtnumquarto;
    private javax.swing.JTextField txtpreco;
    // End of variables declaration//GEN-END:variables
}
