
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author EVARISTO
 */
public class ImprimirFatura extends javax.swing.JFrame {
    String id=DetalhesConta.id;
    String nm,tel,email,nq,cm,tq,de,ds,prc,d,mnt;
    /**
     * Creates new form ImprimirFatura
     */
    public ImprimirFatura() {
        initComponents();
        
        conectar();
        txt.setText("\t=====[> SiGH EVAJOMA <]=====\n");
        txt.setText(txt.getText()+"__________________________________________________\n");
        txt.setText(txt.getText()+"ID da Conta: "+id+"\n");
        txt.setText(txt.getText()+"\t**Detalhes do Cliente**\n");
        txt.setText(txt.getText()+"Nome: "+nm+"\n");
        txt.setText(txt.getText()+"Telefone: "+tel+"\n");
        txt.setText(txt.getText()+"__________________________________________________\n");
        txt.setText(txt.getText()+"\t**Detalhes do Quarto**\n");
        txt.setText(txt.getText()+"Numero do Quarto: "+nq+"\n");
        txt.setText(txt.getText()+"Tipo de Quarto: "+tq+"\n");
        txt.setText(txt.getText()+"Tipo de Cama: "+cm+"\n");
        txt.setText(txt.getText()+"Preco: "+prc+"\n");
        txt.setText(txt.getText()+"Data de entrada: "+de+"\t\tTtl d dias: "+d+"\n");
        txt.setText(txt.getText()+"Data de saida: "+ds+"\t\tValor a pagar: "+mnt+"\n");
        txt.setText(txt.getText()+"__________________________________________________\n");
        txt.setText(txt.getText()+" \t"+"         Muito Obrigado,venha sempre");
    }
    public void conectar(){
        PreparedStatement ps;
        Connection conn;
        ResultSet rs;
        try {
            conn=DriverManager.getConnection("jdbc:mysql://localhost/hotel?user=root&password=");
            ps=conn.prepareStatement("select * from clientes where conta=?");
            ps.setString(1, id);
            rs=ps.executeQuery();
            if(rs.next()){
                nm=rs.getString("nome");
                tel=rs.getString("telefone");
                nq=rs.getString("numquarto");
                cm=rs.getString("cama");
                tq=rs.getString("tipoq");
                de=rs.getString("dataentrada");
                ds=rs.getString("datasaida");
                prc=rs.getString("preco");
                d=rs.getString("dia");
                mnt=rs.getString("montante");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txt = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt.setEditable(false);
        txt.setColumns(20);
        txt.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        txt.setRows(5);
        jScrollPane1.setViewportView(txt);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 32, 450, 310));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/x.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 30, 30));

        jButton2.setBackground(new java.awt.Color(0, 0, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Imprimir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 338, 83, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/espaco-exterior-de-madeira-paisagem-verde-floresta_1417-1033.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 370));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    
        try {
            
txt.print();
        } catch (Exception e) {
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImprimirFatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImprimirFatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImprimirFatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImprimirFatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImprimirFatura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txt;
    // End of variables declaration//GEN-END:variables
}
