
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author EVARISTO
 */
public class SaidaCliente extends javax.swing.JFrame {
    Connection conn;
    Statement st;
    PreparedStatement ps;
    ResultSet rs;
    /**
     * Creates new form SaidaCliente
     */
    public SaidaCliente() {
        initComponents();
        SimpleDateFormat ob=new SimpleDateFormat("yyyy-MM-dd");
        Date data=new Date();
        txtdatasa.setText(ob.format(data));
        try {
            conn=DriverManager.getConnection("jdbc:mysql://localhost/hotel?user=root&password=");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro de conexao em: "+e.getMessage());
        }
        MostrarDataNaTabela();
    }
    public void MostrarDataNaTabela(){
        try {
            ps=conn.prepareStatement("select * from clientes where estado=?");
            ps.setString(1, "null");
            rs=ps.executeQuery();
            ResultSetMetaData ob=rs.getMetaData();
            int n=ob.getColumnCount();
            DefaultTableModel tb= (DefaultTableModel) tabela.getModel();
            tb.setRowCount(0);
            while(rs.next()){
                Vector v=new Vector();
                for(int i=1;i<=n;i++){
                    v.add(rs.getString("nome"));
                    v.add(rs.getString("telefone"));
                    v.add(rs.getString("id"));
                    v.add(rs.getString("numquarto"));
                    v.add(rs.getString("cama"));
                    v.add(rs.getString("tipoq"));
                    v.add(rs.getString("dataentrada"));
                    v.add(rs.getString("preco"));
                    v.add(rs.getString("nacionalidade"));
                }
                tb.addRow(v);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtnumquarto = new javax.swing.JTextField();
        btprocurar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtbi = new javax.swing.JTextField();
        txttelefone = new javax.swing.JTextField();
        txtnome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        txtprecod = new javax.swing.JTextField();
        txtdatae = new javax.swing.JTextField();
        txtdatasa = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txttdia = new javax.swing.JTextField();
        txttconta = new javax.swing.JTextField();
        btremover = new javax.swing.JButton();
        btlimpar = new javax.swing.JButton();
        txtdatas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_cancel_48px_1.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(969, 0, 55, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_hotel_check_out_30px.png"))); // NOI18N
        jLabel1.setText("Saida do Cliente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 11, 212, 52));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Voltar a pagina inicial");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(837, 637, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Numero de Quarto");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        txtnumquarto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txtnumquarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 143, 30));

        btprocurar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btprocurar.setText("Procurar");
        btprocurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btprocurarActionPerformed(evt);
            }
        });
        getContentPane().add(btprocurar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, 90, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nome do Cliente");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 140, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Telefone");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 60, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Bilhete de Identificacao");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, -1, 20));

        txtbi.setEditable(false);
        txtbi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txtbi, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 190, 230, 30));

        txttelefone.setEditable(false);
        txttelefone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txttelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelefoneActionPerformed(evt);
            }
        });
        getContentPane().add(txttelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 200, 30));

        txtnome.setEditable(false);
        txtnome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txtnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 220, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Data de Saida (hoje)");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Preco por dia");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 242, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Data de Entrada");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, -1, -1));

        tabela.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome do Cliente", "Numero de Telefone", "Numero de BI", "Numero de Quarto", "Tipo de Cama", "Tipo de quarto", "Data de Entrada", "Preco", "Nacionalidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 910, 240));

        txtprecod.setEditable(false);
        txtprecod.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txtprecod, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 220, 30));

        txtdatae.setEditable(false);
        txtdatae.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txtdatae, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 200, 30));

        txtdatasa.setEditable(false);
        txtdatasa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txtdatasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 270, 230, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Total de dias");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 314, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Total de Contas");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, -1, -1));

        txttdia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txttdia, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 220, 30));

        txttconta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txttconta, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 200, 30));

        btremover.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btremover.setText("Remover");
        btremover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btremoverActionPerformed(evt);
            }
        });
        getContentPane().add(btremover, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 340, -1, 30));

        btlimpar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btlimpar.setText("Limpar");
        btlimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlimparActionPerformed(evt);
            }
        });
        getContentPane().add(btlimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 340, -1, 30));
        getContentPane().add(txtdatas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int sim=JOptionPane.showConfirmDialog(this, "Tem certeza que quer sair desta pagina?","SAIR",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(sim==JOptionPane.YES_OPTION)
       System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       new PaginaInicial().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txttelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefoneActionPerformed

    private void btremoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btremoverActionPerformed
        try {
            String n="";
            PreparedStatement ps1;
            ps1=conn.prepareStatement("select email from entrars where nome=?");
            ps1.setString(1, "Evaristo");
            rs=ps1.executeQuery();
            while(rs.next()){
            n=rs.getString("email");
            
            }
             ps=conn.prepareStatement("update clientes set estado=?, email=?, datasaida=?, dia=?, montante=? where numquarto=? and dataentrada=?");
             ps.setString(1, "Conta Fechada");
             ps.setString(2, n);
             ps.setString(3, txtdatasa.getText());
             ps.setString(4, txttdia.getText());
             ps.setString(5, txttconta.getText());
             ps.setString(6, txtnumquarto.getText());
             ps.setString(7, txtdatae.getText());
             ps.executeUpdate();
             ps=conn.prepareStatement("update quartos set estado=? where numquarto=?");
             ps.setString(1, "Nao Reservado");
             ps.setString(2, txtnumquarto.getText());
             ps.executeUpdate();
             
             JOptionPane.showConfirmDialog(null, "Conta Fechada com sucesso");
             MostrarDataNaTabela();
             limpar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
       
    }//GEN-LAST:event_btremoverActionPerformed

    private void btprocurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btprocurarActionPerformed
        try {
            ps=conn.prepareStatement("select * from clientes where numquarto=? and estado=?");
            ps.setString(1, txtnumquarto.getText());
            ps.setString(2, "NULL");
            rs=ps.executeQuery();
            while(rs.next()){
                txtnome.setText(rs.getString("nome"));
                txttelefone.setText(rs.getString("telefone"));
                txtbi.setText(rs.getString("id"));
                txtprecod.setText(rs.getString("preco"));
                txtdatae.setText(rs.getString("dataentrada"));
                
                String s1,s2;
                s1=txtdatasa.getText();
                s2=rs.getString("dataentrada");
                SimpleDateFormat dtf=new SimpleDateFormat("yyyy-MM-dd");
                
                Date d1=dtf.parse(s1);
                Date d2=dtf.parse(s2);
                
                long dif=d1.getTime()-d2.getTime();
                int dias=(int)dif/(24*60*60*1000);
                int d=dias+1;

                    txttdia.setText(String.valueOf(d));
                    double preco=Double.parseDouble(rs.getString("preco"))*d;
                    txttconta.setText(String.valueOf(preco));
                
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro em: "+e.getMessage());
        }
    }//GEN-LAST:event_btprocurarActionPerformed

    private void btlimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlimparActionPerformed
        limpar();
    }//GEN-LAST:event_btlimparActionPerformed
public void limpar(){
            txtnome.setText("");
        txtbi.setText("");
        txtdatae.setText("");
        
        txtnumquarto.setText("");
        txtprecod.setText("");
        txttconta.setText("");
        txttdia.setText("");
        txttelefone.setText("");
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaidaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaidaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaidaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaidaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SaidaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btlimpar;
    private javax.swing.JButton btprocurar;
    private javax.swing.JButton btremover;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txtbi;
    private javax.swing.JTextField txtdatae;
    private javax.swing.JLabel txtdatas;
    private javax.swing.JTextField txtdatasa;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtnumquarto;
    private javax.swing.JTextField txtprecod;
    private javax.swing.JTextField txttconta;
    private javax.swing.JTextField txttdia;
    private javax.swing.JTextField txttelefone;
    // End of variables declaration//GEN-END:variables
}
